language: python

python:
  - "2.7"

env:
  - LINT_CHECK="1"
  - VERSION="7.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="7.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"
  - VERSION="7.0" UNIT_TEST="1" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

before_install:
  - sudo pip install GitPython bzr
  - sudo apt-get install bzr
  - sudo pip install cairosvg
  - sudo apt-get install wkhtmltopdf

install:
  - git clone https://github.com/OCA/web.git $HOME/web -b 7.0
  - git clone https://github.com/OCA/pos.git $HOME/pos -b 7.0
  - bzr branch lp:openerp-french-localization/7.0 $HOME/openerp-french-localization
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/OCA/web.git ${HOME}/web
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc

script:
  - travis_run_tests ${VERSION}

after_success:
  coveralls
