addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - "2.7"

env:
  - VERSION="7.0" LINT_CHECK="1"
  - VERSION="7.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0" EXCLUDE="grap_print_product"
  - VERSION="7.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0" EXCLUDE="grap_print_product"
  - VERSION="7.0" UNIT_TEST="1" LINT_CHECK="0" EXCLUDE="grap_print_product"

virtualenv:
  system_site_packages: true

before_install:
  - sudo pip install GitPython bzr
  - sudo apt-get install bzr
  - sudo pip install cairosvg
  - sudo pip install barcode    # FIXME bad version of barcode in pip
  - sudo apt-get install wkhtmltopdf

install:
  - git clone https://github.com/OCA/web.git $HOME/web -b 7.0
  - git clone https://github.com/OCA/pos.git $HOME/pos -b 7.0
  - git clone https://github.com/OCA/l10n-france.git $HOME/l10n-france -b 7.0
  - git clone https://github.com/OCA/sale-workflow.git $HOME/sale-workflow -b 7.0
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc

script:
  - travis_run_tests

after_success:
  coveralls
